# Generated by Django 5.0.1 on 2024-01-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_brutto_weight_products_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cost_for_box',
            field=models.FloatField(default=0, verbose_name='Цена за каробку'),
        ),
        migrations.AlterField(
            model_name='products',
            name='per_box',
            field=models.IntegerField(default=0, verbose_name='Ед. в каробке'),
        ),
    ]
