# Generated by Django 5.0.1 on 2024-01-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_products_cost_alter_products_cost_for_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
