# Generated by Django 5.0.1 on 2024-01-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_tm',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='products',
            name='content_tm',
            field=models.TextField(null=True, verbose_name='Описания'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_tm',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
