# Generated by Django 5.0.1 on 2024-01-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_title_tm_products_content_tm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_tm',
            new_name='title_tk',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='content_tm',
            new_name='content_tk',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='title_tm',
            new_name='title_tk',
        ),
    ]
