# Generated by Django 5.0.1 on 2024-01-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pdfmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFModel',
        ),
    ]
