# Generated by Django 5.0.1 on 2024-01-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='likes',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
