# Generated by Django 5.0.1 on 2024-02-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_tk',
            field=models.TextField(null=True),
        ),
    ]
