# Generated by Django 5.0.1 on 2024-02-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pdf_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
