# Generated by Django 5.0.1 on 2024-02-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_confirmed',
        ),
    ]
