# Generated by Django 5.0.1 on 2024-02-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_userprofile_is_confirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
