# Generated by Django 5.0.1 on 2024-02-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_en',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='category',
            name='img_ru',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='category',
            name='img_tk',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img_en',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img_ru',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img_tk',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
