# Generated by Django 5.0.1 on 2024-02-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_category_img_en_category_img_ru_category_img_tk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img_ru',
        ),
        migrations.RemoveField(
            model_name='products',
            name='img_tk',
        ),
    ]
