# Generated by Django 5.0.1 on 2024-02-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_products_img_en_remove_products_img_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img_tk',
        ),
    ]
